name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: make install
      
      - name: Run Flask server
        run: |
          make run &           
          sleep 10             

      - name: Verify Flask server
        run: curl --fail http://localhost:3000 || exit 1
